core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from registration.views import password_reset_request
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("banks_accounts.urls")),
    path('', include("registration.urls")),
    path('', include("transactions.urls")),
    path('', include('dashboard.urls')),
    path('', views.home, name='home'),



    path('change_password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change_password.html', success_url='/password_change_done/'),
         name='change_password'),
    path('forgot_password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/forgot-password.html', success_url='/password_change_done/'),
         name='change_password'),
    path("password_reset", password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from registration.views import password_reset_request
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("banks_accounts.urls")),
    path('', include("registration.urls")),
    path('', include("transactions.urls")),
    path('', include('dashboard.urls')),
    path("select2/", include("django_select2.urls")),
    path('', views.home, name='home'),



    path('change_password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change_password.html', success_url='/password_change_done/'),
         name='change_password'),
    path('forgot_password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/forgot-password.html', success_url='/password_change_done/'),
         name='change_password'),
    path("password_reset", password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

transactions/models.py
import os
from django.contrib.auth.models import User
from django.db import models

from banks_accounts.models import Accounts, Account_types


class Category(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    name = models.CharField(max_length=200, null=True, blank=True, verbose_name='Categoria')

    def __str__(self):
        return self.name


class Transactions(models.Model):
    INCOMES = 'Receitas'
    EXPENSES = 'Despesas'

    TYPE_CHOICES = [
        ('', '---------'),
        (INCOMES, 'Receitas'),
        (EXPENSES, 'Despesas'),
    ]

    FREQUENCIES = [
        ('', '---------'),
        ('Diariamente', 'Diariamente'),
        ('Semanalmente', 'Semanalmente'),
        ('Mensalmente', 'Mensalmente'),
        ('Anualmente', 'Anualmente'),
    ]

    class Meta:
        ordering = ['description']
        verbose_name = 'Transação'
        verbose_name_plural = 'Transações'

    accounts = models.ForeignKey(Accounts, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Conta')
    account_type = models.ForeignKey(Account_types,
                                     on_delete=models.CASCADE, null=True, blank=True, verbose_name='Tipo de conta')
    attachments = models.FileField(upload_to="attachments/",
                                   max_length=200, null=True, blank=True, verbose_name='Anexos')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Categoria')
    date_transaction = models.DateField(auto_created=False, verbose_name='Data da Transação')
    description = models.CharField(max_length=200, null=True, blank=True, verbose_name='Descrição')
    note = models.CharField(max_length=500, verbose_name='Observação')
    paid = models.BooleanField(default=False, verbose_name='Pago')
    recurring = models.BooleanField(default=False, verbose_name='Repete')
    select = models.CharField(max_length=12,
                              default='', blank=False, null=False, choices=FREQUENCIES, verbose_name='Frequência')
    paid_installment = models.PositiveIntegerField(null=True, blank=True, verbose_name='Parcela paga')
    total_installments = models.IntegerField(null=True, blank=True, verbose_name='Parcelas Totais')
    type = models.CharField(max_length=10,
                            default='', blank=False, null=False, choices=TYPE_CHOICES, verbose_name='Despesas e Receita')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')
    user = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, verbose_name='Usuário')
    value = models.FloatField(default=0.0, null=False, blank=True, verbose_name='Valor')

    def __str__(self):
        if self.description is not None:
            return str(self.accounts) + " - " + self.description.upper()
        else:
            return str(self.accounts)

    @property
    def filename(self):
        return os.path.basename(self.attachments.name)

templates/base/base.html
<!DOCTYPE html>
<html lang="pt-br">
<title>{% block titulo %}{% endblock %} FINANS</title>


<!--Headers-->
{% include 'base/header.html' %}
<!--Navbar-->
{% include 'base/navbar.html' %}
<body class="app header-fixed sidebar-fixed">
<div class="app-body bg-light " id="loading">
    <!-- Main content -->
    <main class="main">

        <!-- Breadcrumb -->
        {% include 'base/breadcrumb.html' %}
        <!-- Page contents -->
        <div class="animated fadeIn">
            {% block content %}
            
            {% endblock %}
        </div>
    </main>
</div>

<!--Footer-->
{% include 'base/footer.html' %}

<!--JS-->
{% include 'base/js.html' %}
</body>
</html>

templates/base/breadcrumb.html
{% load static %}

<ol class="breadcrumb">
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down mt-2 mb-2 me-5">
        <div class="btn-group" role="group" aria-label="Button group">
            <a class="btn" href="{% url 'home' %}"><i class="fa fa-home"></i> &nbsp;Dashboard</a>
            <a class="btn" href="{% url 'list_transactions' %}"><i class="fa fa-dollar"></i> &nbsp;Lançamentos</a>
            <a class="btn" href="{% url 'charts' %}"><i class="fa fa-pie-chart"></i> &nbsp;Relatórios</a>
        </div>
    </li>
    {% block breadcrumb %}
    {% endblock %}
</ol>

templates/base/footer.html
<footer class="app-footer">
    <span><a href="#">FINANS</a> © 2024</span>
    <span class="ml-auto">Created by <a href="#">Cícero Régis</a></span>
    {% block extrafooter %}
    {% endblock %}
</footer>

templates/base/header.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="FINANS - Aplicação financeira pessoal é que ajuda a gerenciar suas finanças pessoais.">
    <meta name="author" content="Cícero Régis">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="{% static 'dist/img/favicon.png' %}">


    <!-- Icons -->
    <link href="{% static 'dist/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'dist/vendors/css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'dist/css/jquery.datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/pace-loading-bar.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css" />-->
    <link rel="stylesheet" href="https://cdn.datatables.net/rowreorder/1.5.0/css/rowReorder.dataTables.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/3.0.0/css/responsive.dataTables.css"/>



    {% block extrahead %}
    {% endblock %}
</head>

templates/base/js.html
{% load static %}
<!-- Bootstrap and necessary plugins -->
<script src="{% static 'dist/vendors/js/jquery.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/popper.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/bootstrap.min.js' %}"></script>
<script src="{% static 'dist/vendors/js/pace.min.js' %}"></script>
<script src="{% static 'dist/js/views/main.js' %}"></script>
<script src="{% static 'dist/js/app.js' %}"></script>

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
  integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
  integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
  crossorigin="anonymous"
></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'dist/vendors/js/jquery.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pace-js@latest/pace.min.js"></script>
<script src="https://cdn.datatables.net/2.0.2/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.2/js/dataTables.bootstrap5.js"></script>
<script src="https://cdn.datatables.net/rowreorder/1.5.0/js/dataTables.rowReorder.js"></script>
<script src="https://cdn.datatables.net/rowreorder/1.5.0/js/rowReorder.dataTables.js"></script>
<script src="https://cdn.datatables.net/responsive/3.0.0/js/dataTables.responsive.js"></script>
<script src="https://cdn.datatables.net/responsive/3.0.0/js/responsive.dataTables.js"></script>


<script>
  // tooltip data
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });

  $(document).ready(function () {
    $('.select2').select2();
  });

  // calendar component
  $(function () {
      // Configura o componente de calendário
      $.datetimepicker.setLocale('pt-BR');
      $('#datetimepicker').datetimepicker({
        timepicker: false,
        format: 'd/m/Y',
      });

      // Obtém a referência da tabela e da coluna de data
      const table = document.getElementById('table');
      const dateColumn = 6; // Índice da coluna de data

      // Adiciona um evento de mudança ao campo de entrada de data
      $('#datetimepicker').change(function () {
        const filterText = $(this).val().toLowerCase();

        // Itera sobre as linhas da tabela, começando da segunda linha (índice 1) para ignorar o cabeçalho
        $(table).find('tbody tr').each(function () {
          const dateValue = $(this).find('td').eq(dateColumn).text().toLowerCase();
          if (dateValue.includes(filterText)) {
            $(this).show(); // Exibe a linha se o valor da coluna de data incluir o texto de filtro
          } else {
            $(this).hide(); // Oculta a linha caso contrário
          }
        });
      });
    });

  // select repeat input
  document.addEventListener('DOMContentLoaded', function () {
    const checkbox = document.getElementById('checkbox');
    const select = document.getElementById('select');
    const totalInstallments = document.getElementById('total_installments');

    function updateDisplay() {
      const isChecked = checkbox.checked;

      if (isChecked) {
        select.style.display = 'inline-block';
        totalInstallments.style.display = 'inline-block';
      } else {
        select.style.display = 'none';
        totalInstallments.style.display = 'none';
      }
    }

    // Initial state check
    updateDisplay();

    // Checkbox change event
    checkbox.addEventListener('change', updateDisplay);
  });

  // search input table
  $(document).ready(function () {
    $('#filter').on('change', function () {
        const value = $(this).val();
        if (value === 'revenue') {
            $('#table tbody tr').show();
            $('#table tbody tr .transaction.expense').closest('tr').hide();
        } else if (value === 'expense') {
            $('#table tbody tr').show();
            $('#table tbody tr .transaction.revenue').closest('tr').hide();
        } else {
            $('#table tbody tr').show();
        }
    });
});


  setInterval(function () {
    var button = document.getElementById('notificationButton');
    if (button) {
      button.classList.toggle('flash');
    }
  }, 1000);



  function calculateMonthsSinceStart(selectedDate) {
    const startDate = new Date();
    const monthsSinceStart =
        (selectedDate.getFullYear() - startDate.getFullYear()) * 12 +
        (selectedDate.getMonth() - startDate.getMonth());
    return monthsSinceStart;
}

  function showInstallments(date, totalInstallments) {
    try {
      // Converte o formato da data para um formato que o construtor Date possa entender
      var selectedDate = parseCustomDate(date);
      const monthsSinceStart = calculateMonthsSinceStart(selectedDate);
      // Calcula o número de meses desde o início do pagamento
      var currentInstallment = monthsSinceStart + 2;
      // Atualiza a exibição na página
      var installmentsValue = document.getElementById('installmentsValue');
      if (
        !isNaN(currentInstallment) && currentInstallment <= totalInstallments && currentInstallment >= 0) {
        installmentsValue.innerText =
          currentInstallment + '/' + totalInstallments;
      } else {
        installmentsValue.innerText = 'Todos os pagamentos foram concluídos.';
      }
    }catch{

    }
    
  }

  // Função auxiliar para converter o formato específico da data
  function parseCustomDate(dateString) {
    var monthMap = {
      Janeiro: 1,
      Fevereiro: 2,
      Março: 3,
      Abril: 4,
      Maio: 5,
      Junho: 6,
      Julho:7,
      Agosto: 8,
      Setembro: 9,
      Outubro: 10,
      Novembro: 11,
      Dezembro: 12,
    };

    var parts = dateString.split(' ');

    var month = parts[2];
    var year = parts[4];

    var monthNumber = monthMap[month];

    return new Date(year, monthNumber);
  }

  function tabpaid(tackedtab) {
    if (tackedtab) {
      return 'pago';
    }
  }

  const guia1 = true; 
  const guia2 = false; 

  $(document).ready(function () {
    function payForTabs(transactionId, tabNumbers) {
      $.ajax({
        type: 'POST',
        url: '{% url "mark_account_as_paid_this_month" 0 %}'.replace(
          '0',
          transactionId
        ),
        data: {
          csrfmiddlewaretoken: '{{ csrf_token }}',
          transaction_id: transactionId,
          tab_numbers: tabNumbers.join(','), 
        },
        success: function (data) {
          if (data.success) {
            // Remove a classe 'active' e 'paid' de todas as guias e botões "Pagar"
            $('.nav-link, .pagar-button').removeClass('active paid');

            // Adiciona a classe 'active' e 'paid' apenas à guia e botão "Pagar" dos meses pagos
            $.each(data.paid_installments, function (index, paidInstallment) {
              $('.tab-' + paidInstallment).addClass('active paid');
              location.reload();
            });
          } else {
            alert(data.error);
          }
        },
        error: function (error) {
          location.reload();
        },
      });
    }

    $('.pagar-button').click(function (e) {
      e.preventDefault();

      var transactionId = $(this).data('transaction-id');
      var tabNumber = $(this).data('tab-number');

      // Verifica se a guia já está marcada
      if ($(this).hasClass('active')) {
        $(this).removeClass('active');
      } else {
        $(this).addClass('active');
      }

      // Obtém os números das guias marcadas
      var tabNumbers = [];
      $('.pagar-button.active').each(function () {
        tabNumbers.push($(this).data('tab-number'));
      });

      payForTabs(transactionId, tabNumbers);
    });

    function updatePaidStatus() {
      // Verifica se todas as guias estão marcadas como pagas
      var allTabsMarked =
        $('.nav-link').length === $('.pagar-button.active').length;

      // Atualiza o campo form.paid conforme necessário
      $('#id_paid').prop('checked', allTabsMarked);
    }

    $('.pagar-button').click(function (e) {
      e.preventDefault();

      var tabNumber = $(this).data('tab-number');

      // Verifica se a guia já está marcada
      if ($(this).hasClass('active')) {
        $(this).removeClass('active');
      } else {
        $(this).addClass('active');
      }

      updatePaidStatus();
    });
  });
  // Config table
    let table = new DataTable('.dataTableStyle', {
    "language": {
            "lengthMenu": "_MENU_ por página",
            "info": "Mostrando página _PAGE_ de _PAGES_",
            "infoEmpty": "Nenhuma pagina disponível ",
            "infoFiltered": "(Filtrado from _MAX_ total registros)"
        },
        layout: {

        topStart: {
            pageLength: {
                menu: [ 2, 5, 10, 25, 50, { label: 'Todos', value: -1 } ]
            }
        }
        },
        select: {
        style: 'single'
    },

     paging: true,
     pageLength: 10,
     responsive: true,
     searching: false,
   });

</script>
{% block script %} {% endblock %}

templates/base/messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
        </div>
    {% endfor %}
{% endif %}

templates/base/navbar.html
{% load static %}
<header class=" mb-6 app-header navbar" style="background-color: #004672">
        <a class="navbar-brand" href="#" style="background-color: #004672;">
  <h4 class="text-white">FINANS</h4>
</a>
</span>
    <ul class="nav navbar-nav ml-auto ml-sm-auto ms-3">
        {% if user.is_authenticated %}
        <p class="mb-0 d-none d-lg-block text-white">Bem-vindo(a) <strong>{{ user.first_name|capfirst }}</strong></p>
        {% endif %}
        <li class="nav-item dropdown col-md-3 col-lg-2">
            <a class="nav-link py-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">

                <div class="avatar avatar-sm">
                    <img src="{% static '/dist/img/avatars/avatar_profile.png' %}"
                         class="img-avatar" alt="avatar_profile">
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">

                <div class="dropdown-header text-center">
                    <strong>Conta</strong>
                </div>
                {% if user.is_superuser %}
                <a class="dropdown-item" target="_blank" href="{% url 'admin:index' %}">
                    <i class="fa fa-gears"></i>Administrador
                </a>
                {% endif %}
                <div class="dropdown-header text-center">
                    <strong>Settings</strong>
                </div>

                <a class="dropdown-item" href="{% url 'user_profile' %}">
                    <i class="fa fa-user"></i>Perfil</a>
                

                <form id="logout-form" method="post" action="{% url 'logout' %}" >
                    {% csrf_token %}
                    <a class="dropdown-item" href="{% url 'logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out"></i> Logout
                    </a>    
                </form>
            </div>
        </li>
    </ul>
    {% block navbar %} {% endblock %}

</header>

templates/base/pagination.html
{% load static %}
<nav aria-label="Page navigation">
    <!--<div class="mt-2" style="display: flex; justify-content: flex-end;">
        <p class="me-5">Página {{ page.number }} de {{ page.paginator.num_pages }}</p>
        <span class="page-number me-4">
            <strong> Total de Registros </strong> {{ page | length}}
        </span>
    </div>-->

    <ul class="pagination pagination-sm justify-content-center">

        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for page_num in page.paginator.page_range %}
        {% if page.number == page_num %}
        <li class="page-item active" aria-current="page">
            <span class="page-link">{{ page_num }}</span>
        </li>
        {% elif page_num > page.number|add:-2 and page_num < page.number|add:2 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% elif page_num == page.paginator.page_range.first or page_num == page.paginator.page_range.last %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% elif page_num == page.number|add:-4 or page_num == page.number|add:4 %}
        <li class="page-item disabled">
            <span class="page-link">... </span>
        </li>
        {% elif page_num < page.number|add:-2 or page_num < page.number|add:2 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% elif page_num > page.number|add:-5 and page_num > page.number|add:5 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>

</nav>

templates/base/sidebar.html
<!-- <div class="sidebar sidebar-show sidebar-dark sidebar-fixed">
  <nav class="sidebar-brand d-md-flex">
    <ul class="nav sidebar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">
          <i class="nav-icon icon-home"></i> Dashboard
        </a>
      </li>

      <li class="nav-title">Components</li>
      <li class="nav-item nav-dropdown navbar-green">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-puzzle"></i> Base</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Breadcrumb</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Cards</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Carousel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Collapse</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Forms</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Jumbotron</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> List group</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Navs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Pagination</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Popovers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Progress</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Scrollspy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Switches</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Tables</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Tabs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="nav-icon icon-puzzle"></i> Tooltips</a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>
-->